User Thresholding
bigdatagenomics/gnocchi pull request #13
Opened 2017-02-08 18:26 UTC by nathanielparke

Allows a user to set a threshold for classification in the logistic regression suite for EvaluateModel.

2017-02-08 18:30 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-02-17 20:05 UTC, devin-petersohn commented
pinging @fnothaft @heuermh to approve Jenkins build test.

2017-02-24 17:01 UTC, heuermh requested changes

2017-02-24 17:01 UTC, heuermh commented on gnocchi-core/src/test/scala/net/fnothaft/gnocchi/association/LogisticValidationRegressionSuite.scala
> +    val pathToFile = ClassLoader.getSystemClassLoader.getResource("binaryThreshold3.csv").getFile
bdg-utils `SparkFunSuite` provides a `testFile` method

https://github.com/bigdatagenomics/utils/blob/master/utils-misc/src/test/scala/org/bdgenomics/utils/misc/SparkFunSuite.scala#L116

2017-02-24 17:01 UTC, heuermh commented on gnocchi-core/src/test/scala/net/fnothaft/gnocchi/association/LogisticValidationRegressionSuite.scala
> +        print("Error --> ")
these debugging statements shouldn't be left in, make assertions and let the test framework report errors

2017-03-01 13:14 UTC, heuermh commented
Jenkins, add to whitelist

2017-03-07 18:16 UTC, closed without merging