Write filtered phenotypes to a file flag
bigdatagenomics/gnocchi pull request #17
Opened 2017-02-15 19:15 UTC by nathanielparke

This PR allows a command line user to chose to write all the filtered phenotypes to a directory of their choosing. Useful for debugging data issues.

2017-02-15 19:16 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-02-17 20:05 UTC, devin-petersohn commented
pinging @fnothaft @heuermh to approve Jenkins build test.

2017-02-24 16:57 UTC, heuermh requested changes

2017-02-24 16:57 UTC, heuermh commented on gnocchi-core/src/test/scala/net/fnothaft/gnocchi/association/LogisticValidationRegressionSuite.scala
> +        print("Error --> ")
these debugging statements shouldn't be left in, make assertions and let the test framework report errors

2017-02-24 16:57 UTC, heuermh commented on gnocchi-cli/src/main/scala/net/fnothaft/gnocchi/cli/RegressPhenotypes.scala
> +  @Args4jOption(required = false, name = "-writeMissingPheno", usage = "Write missing phenotypes to the location supplied.")
for better or worse ADAM cli uses `-single_dash_snake_case` for command line arguments

2017-03-01 13:14 UTC, heuermh commented
Jenkins, add to whitelist

2017-03-07 18:16 UTC, closed without merging