Instrumentation for RegressPhenotypes
bigdatagenomics/gnocchi pull request #18
Opened 2017-02-15 20:10 UTC by nathanielparke

Adds in instrumentation for RegressPhenotypes which can be ported to other section of code when the need arises.

2017-02-15 20:10 UTC, AmplabJenkins commented
Can one of the admins verify this patch?

2017-02-17 20:05 UTC, devin-petersohn commented
pinging @fnothaft @heuermh to approve Jenkins build test.

2017-02-18 00:58 UTC, heuermh commented
I was waiting on a successful build for #12 before adding other pull requests to Jenkins.

2017-02-24 16:53 UTC, heuermh requested changes

2017-02-24 16:53 UTC, heuermh commented on gnocchi-cli/src/main/scala/net/fnothaft/gnocchi/cli/RegressPhenotypes.scala
> +  def print_metrics_to_cmdline(metricsListener: MetricsListener) {
use camelCase for method names

2017-02-24 16:53 UTC, heuermh commented on gnocchi-cli/src/main/scala/net/fnothaft/gnocchi/cli/RegressPhenotypes.scala
> +  @Args4jOption(required = false, name = "-time", usage = "Prints out the timing information for RegressPhenotypes to commandline.")
in ADAM we use `-print_metrics` for this, which comes from bdg-utils 

https://github.com/bigdatagenomics/utils/blob/master/utils-cli/src/main/scala/org/bdgenomics/utils/cli/Args4j.scala#L26

Or am I missing the use case here?

2017-02-24 16:53 UTC, heuermh commented on gnocchi-cli/src/main/scala/net/fnothaft/gnocchi/cli/RegressPhenotypes.scala
> +    Metrics.initialize(sc)
this is also handled in bdg-utils for the `-print_metrics` argument

https://github.com/bigdatagenomics/utils/blob/master/utils-cli/src/main/scala/org/bdgenomics/utils/cli/BDGCommand.scala#L68

2017-03-01 13:14 UTC, heuermh commented
Jenkins, add to whitelist

2017-03-07 18:16 UTC, closed without merging